// This file is autogenerated by lib/feature-plugin.js
import { expose } from 'comlink';
import { timed } from './util';
import resize from './../features/processors/resize/worker/resize';
import quantize from './../features/processors/quantize/worker/quantize';
import rotate from './../features/preprocessors/rotate/worker/rotate';
import webpDecode from './../features/decoders/webp/worker/webpDecode';
import wp2Decode from './../features/decoders/wp2/worker/wp2Decode';
import qoiDecode from './../features/decoders/qoi/worker/qoiDecode';
import jxlDecode from './../features/decoders/jxl/worker/jxlDecode';
import avifDecode from './../features/decoders/avif/worker/avifDecode';
import wp2Encode from './../features/encoders/wp2/worker/wp2Encode';
import webpEncode from './../features/encoders/webP/worker/webpEncode';
import qoiEncode from './../features/encoders/qoi/worker/qoiEncode';
import oxipngEncode from './../features/encoders/oxiPNG/worker/oxipngEncode';
import mozjpegEncode from './../features/encoders/mozJPEG/worker/mozjpegEncode';
import jxlEncode from './../features/encoders/jxl/worker/jxlEncode';
import avifEncode from './../features/encoders/avif/worker/avifEncode';
const exports = {
    resize(...args) {
        return timed('resize', () => resize(...args));
    },
    quantize(...args) {
        return timed('quantize', () => quantize(...args));
    },
    rotate(...args) {
        return timed('rotate', () => rotate(...args));
    },
    webpDecode(...args) {
        return timed('webpDecode', () => webpDecode(...args));
    },
    wp2Decode(...args) {
        return timed('wp2Decode', () => wp2Decode(...args));
    },
    qoiDecode(...args) {
        return timed('qoiDecode', () => qoiDecode(...args));
    },
    jxlDecode(...args) {
        return timed('jxlDecode', () => jxlDecode(...args));
    },
    avifDecode(...args) {
        return timed('avifDecode', () => avifDecode(...args));
    },
    wp2Encode(...args) {
        return timed('wp2Encode', () => wp2Encode(...args));
    },
    webpEncode(...args) {
        return timed('webpEncode', () => webpEncode(...args));
    },
    qoiEncode(...args) {
        return timed('qoiEncode', () => qoiEncode(...args));
    },
    oxipngEncode(...args) {
        return timed('oxipngEncode', () => oxipngEncode(...args));
    },
    mozjpegEncode(...args) {
        return timed('mozjpegEncode', () => mozjpegEncode(...args));
    },
    jxlEncode(...args) {
        return timed('jxlEncode', () => jxlEncode(...args));
    },
    avifEncode(...args) {
        return timed('avifEncode', () => avifEncode(...args));
    },
};
// 'as any' to work around the way our client code has insight into worker code
expose(exports, self);
