import resize from './../features/processors/resize/worker/resize';
import quantize from './../features/processors/quantize/worker/quantize';
import rotate from './../features/preprocessors/rotate/worker/rotate';
import webpDecode from './../features/decoders/webp/worker/webpDecode';
import wp2Decode from './../features/decoders/wp2/worker/wp2Decode';
import qoiDecode from './../features/decoders/qoi/worker/qoiDecode';
import jxlDecode from './../features/decoders/jxl/worker/jxlDecode';
import avifDecode from './../features/decoders/avif/worker/avifDecode';
import wp2Encode from './../features/encoders/wp2/worker/wp2Encode';
import webpEncode from './../features/encoders/webP/worker/webpEncode';
import qoiEncode from './../features/encoders/qoi/worker/qoiEncode';
import oxipngEncode from './../features/encoders/oxiPNG/worker/oxipngEncode';
import mozjpegEncode from './../features/encoders/mozJPEG/worker/mozjpegEncode';
import jxlEncode from './../features/encoders/jxl/worker/jxlEncode';
import avifEncode from './../features/encoders/avif/worker/avifEncode';
declare const exports: {
    resize(data: ImageData, opts: import("../features/processors/resize/shared/meta").WorkerResizeOptions): ReturnType<typeof resize>;
    quantize(data: ImageData, opts: import("../features/processors/quantize/shared/meta").Options): ReturnType<typeof quantize>;
    rotate(data: ImageData, opts: import("../features/preprocessors/rotate/shared/meta").Options): ReturnType<typeof rotate>;
    webpDecode(blob: Blob): ReturnType<typeof webpDecode>;
    wp2Decode(blob: Blob): ReturnType<typeof wp2Decode>;
    qoiDecode(blob: Blob): ReturnType<typeof qoiDecode>;
    jxlDecode(blob: Blob): ReturnType<typeof jxlDecode>;
    avifDecode(blob: Blob): ReturnType<typeof avifDecode>;
    wp2Encode(data: ImageData, options: import("codecs/wp2/enc/wp2_enc").EncodeOptions): ReturnType<typeof wp2Encode>;
    webpEncode(data: ImageData, options: import("codecs/webp/enc/webp_enc").EncodeOptions): ReturnType<typeof webpEncode>;
    qoiEncode(data: ImageData, options: import("codecs/qoi/enc/qoi_enc").EncodeOptions): ReturnType<typeof qoiEncode>;
    oxipngEncode(data: ImageData, options: import("../features/encoders/oxiPNG/shared/meta").EncodeOptions): ReturnType<typeof oxipngEncode>;
    mozjpegEncode(data: ImageData, options: import("codecs/mozjpeg/enc/mozjpeg_enc").EncodeOptions): ReturnType<typeof mozjpegEncode>;
    jxlEncode(data: ImageData, options: import("codecs/jxl/enc/jxl_enc").EncodeOptions): ReturnType<typeof jxlEncode>;
    avifEncode(data: ImageData, options: import("codecs/avif/enc/avif_enc").EncodeOptions): ReturnType<typeof avifEncode>;
};
export type ProcessorWorkerApi = typeof exports;
export {};
