// This file is autogenerated by lib/feature-plugin.js
import * as webPEncoderMeta from '../../../features/encoders/webP/shared/meta';
import * as wp2EncoderMeta from '../../../features/encoders/wp2/shared/meta';
import * as qoiEncoderMeta from '../../../features/encoders/qoi/shared/meta';
import * as oxiPNGEncoderMeta from '../../../features/encoders/oxiPNG/shared/meta';
import * as mozJPEGEncoderMeta from '../../../features/encoders/mozJPEG/shared/meta';
import * as jxlEncoderMeta from '../../../features/encoders/jxl/shared/meta';
import * as browserPNGEncoderMeta from '../../../features/encoders/browserPNG/shared/meta';
import * as browserJPEGEncoderMeta from '../../../features/encoders/browserJPEG/shared/meta';
import * as browserGIFEncoderMeta from '../../../features/encoders/browserGIF/shared/meta';
import * as avifEncoderMeta from '../../../features/encoders/avif/shared/meta';
import * as webPEncoderEntry from '../../../features/encoders/webP/client';
import * as wp2EncoderEntry from '../../../features/encoders/wp2/client';
import * as qoiEncoderEntry from '../../../features/encoders/qoi/client';
import * as oxiPNGEncoderEntry from '../../../features/encoders/oxiPNG/client';
import * as mozJPEGEncoderEntry from '../../../features/encoders/mozJPEG/client';
import * as jxlEncoderEntry from '../../../features/encoders/jxl/client';
import * as browserPNGEncoderEntry from '../../../features/encoders/browserPNG/client';
import * as browserJPEGEncoderEntry from '../../../features/encoders/browserJPEG/client';
import * as browserGIFEncoderEntry from '../../../features/encoders/browserGIF/client';
import * as avifEncoderEntry from '../../../features/encoders/avif/client';
export const encoderMap = {
    webP: { meta: webPEncoderMeta, ...webPEncoderEntry },
    wp2: { meta: wp2EncoderMeta, ...wp2EncoderEntry },
    qoi: { meta: qoiEncoderMeta, ...qoiEncoderEntry },
    oxiPNG: { meta: oxiPNGEncoderMeta, ...oxiPNGEncoderEntry },
    mozJPEG: { meta: mozJPEGEncoderMeta, ...mozJPEGEncoderEntry },
    jxl: { meta: jxlEncoderMeta, ...jxlEncoderEntry },
    browserPNG: { meta: browserPNGEncoderMeta, ...browserPNGEncoderEntry },
    browserJPEG: { meta: browserJPEGEncoderMeta, ...browserJPEGEncoderEntry },
    browserGIF: { meta: browserGIFEncoderMeta, ...browserGIFEncoderEntry },
    avif: { meta: avifEncoderMeta, ...avifEncoderEntry },
};
import * as resizeProcessorMeta from '../../../features/processors/resize/shared/meta';
import * as quantizeProcessorMeta from '../../../features/processors/quantize/shared/meta';
export const defaultProcessorState = {
    resize: { enabled: false, ...resizeProcessorMeta.defaultOptions },
    quantize: { enabled: false, ...quantizeProcessorMeta.defaultOptions },
};
import * as rotatePreprocessorMeta from '../../../features/preprocessors/rotate/shared/meta';
export const defaultPreprocessorState = {
    rotate: rotatePreprocessorMeta.defaultOptions,
};
